2020-10-27 16:05:33,361 -  dev bleu:   1.56 [Beam search decoding with beam size = 10 and alpha = 1.0]
Traceback (most recent call last):
  File "/home/students/koss/anaconda3/envs/venv/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/students/koss/anaconda3/envs/venv/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/students/koss/bachelor/joeynmt/joeynmt/__main__.py", line 41, in <module>
    main()
  File "/home/students/koss/bachelor/joeynmt/joeynmt/__main__.py", line 31, in main
    test(cfg_file=args.config_path, ckpt=args.ckpt,
  File "/home/students/koss/bachelor/joeynmt/joeynmt/prediction.py", line 405, in test
    with open(output_path_set, mode="w", encoding="utf-8") as out_file:
FileNotFoundError: [Errno 2] No such file or directory: 'results/test_best_raw/.dev'
srun: error: gpu03: task 0: Exited with exit code 1
